# Generated by Django 3.2.4 on 2021-06-28 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('start', models.CharField(max_length=200, null=True)),
                ('end', models.CharField(max_length=200, null=True)),
                ('departureTime', models.DateTimeField(auto_now_add=True)),
                ('capacity', models.IntegerField(default=120)),
                ('purchased', models.IntegerField(default=0)),
                ('price', models.FloatField(default=500)),
                ('rownum', models.IntegerField(default=20)),
                ('columnnum', models.IntegerField(default=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('未支付', '未支付'), ('已支付', '已支付'), ('已取票', '已取票')], max_length=200, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatrow', models.IntegerField(null=True)),
                ('seatcolumn', models.IntegerField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.flight')),
            ],
            options={
                'unique_together': {('customer', 'flight')},
            },
        ),
    ]
