# Generated by Django 3.2.4 on 2021-06-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departureTime',
            field=models.DateTimeField(),
        ),
    ]
